class RepoErrors(Exception):
    pass


class ValidErrors(Exception):
    pass


